name: Enable Auto Merge on PRs

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Enable auto-merge for PRs
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash

